pipeline:
  name: AIO
  identifier: AIO
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Shell
        identifier: Shell
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Bash
                    command: echo hello
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        tags: {}
    - stage:
        name: HTTP
        identifier: HTTP
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: Harness API
                  identifier: Harness_API
                  spec:
                    url: https://app.harness.io/pipeline/api/pipeline/execute/<+pipeline.variables.PIPELINE_IDENTIFIER>/inputSetList?accountIdentifier=0e6wLndETGC6pO20LQZHpA&orgIdentifier=default&projectIdentifier=default_project&notesForPipelineExecution=AIO
                    method: POST
                    headers:
                      - key: x-api-key
                        value: <+pipeline.variables.HARNESS_API_KEY>
                      - key: Content-Type
                        value: application/json
                    inputVariables: []
                    outputVariables: []
                    requestBody: |-
                      {
                        "inputSetReferences": [
                          "mmtt"
                        ]
                      }
                    delegateSelectors:
                      - docker-delegate
                  timeout: 1m
        tags: {}
  variables:
    - name: HARNESS_API_KEY
      type: Secret
      description: ""
      required: true
      value: <+input>
    - name: PIPELINE_IDENTIFIER
      type: String
      description: ""
      required: true
      value: <+input>
