pipeline:
  name: AIO
  identifier: AIO
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Shell
        identifier: Shell
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        tags: {}
  variables:
    - name: test
      type: Secret
      description: ""
      required: true
      value: <+input>
    - name: PIPELINE_NAME
      type: String
      description: ""
      required: true
      value: <+pipeline.delegateSelectors>
